### ISSUE TITLE
column objkt.minterId does not exist

### ISSUE THREAD

**Issue by iworkinprogress** [fxhash/fxhash-api#31]
I'm getting an error when trying to query for an Objkt in the Graphql Sandbox. 

It's entirely possible I messed something up while setting up Docker...but is this an issue anyone has seen before?

The query:
```
query ExampleQuery {
  objkts {
    id
  }
}
```

Gives me the below error:
```
{
  "errors": [
    {
      "message": "column objkt.minterId does not exist",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "objkts"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "SELECT DISTINCT \"distinctAlias\".\"objkt_id\" as \"ids_objkt_id\", \"distinctAlias\".\"objkt_id\" FROM (SELECT \"objkt\".\"id\" AS \"objkt_id\", \"objkt\".\"slug\" AS \"objkt_slug\", \"objkt\".\"issuerId\" AS \"objkt_issuerId\", \"objkt\".\"ownerId\" AS \"objkt_ownerId\", \"objkt\".\"minterId\" AS \"objkt_minterId\", \"objkt\".\"name\" AS \"objkt_name\", \"objkt\".\"assigned\" AS \"objkt_assigned\", \"objkt\".\"iteration\" AS \"objkt_iteration\", \"objkt\".\"generationHash\" AS \"objkt_generationHash\", \"objkt\".\"duplicate\" AS \"objkt_duplicate\", \"objkt\".\"metadata\" AS \"objkt_metadata\", \"objkt\".\"metadataUri\" AS \"objkt_metadataUri\", \"objkt\".\"tags\" AS \"objkt_tags\", \"objkt\".\"features\" AS \"objkt_features\", \"objkt\".\"rarity\" AS \"objkt_rarity\", \"objkt\".\"royalties\" AS \"objkt_royalties\", \"objkt\".\"version\" AS \"objkt_version\", \"objkt\".\"createdAt\" AS \"objkt_createdAt\", \"objkt\".\"assignedAt\" AS \"objkt_assignedAt\" FROM \"objkt\" \"objkt\" LEFT JOIN \"generative_token\" \"issuer\" ON \"issuer\".\"id\"=\"objkt\".\"issuerId\") \"distinctAlias\" ORDER BY \"distinctAlias\".\"objkt_id\" DESC NULLS LAST, \"objkt_id\" ASC LIMIT 20",
          "parameters": [],
          "driverError": {
            "length": 173,
            "name": "error",
            "severity": "ERROR",
            "code": "42703",
            "hint": "Perhaps you meant to reference the column \"objkt.ownerId\".",
            "position": "241",
            "file": "parse_relation.c",
            "line": "3504",
            "routine": "errorMissingColumn"
          },
          "length": 173,
          "severity": "ERROR",
          "code": "42703",
          "hint": "Perhaps you meant to reference the column \"objkt.ownerId\".",
          "position": "241",
          "file": "parse_relation.c",
          "line": "3504",
          "routine": "errorMissingColumn",
          "stacktrace": [
            "QueryFailedError: column objkt.minterId does not exist",
            "    at QueryFailedError.TypeORMError [as constructor] (/app/node_modules/src/error/TypeORMError.ts:7:9)",
            "    at new QueryFailedError (/app/node_modules/src/error/QueryFailedError.ts:9:9)",
            "    at PostgresQueryRunner.<anonymous> (/app/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:263:19)",
            "    at step (/app/node_modules/tslib/tslib.js:144:27)",
            "    at Object.throw (/app/node_modules/tslib/tslib.js:125:57)",
            "    at rejected (/app/node_modules/tslib/tslib.js:116:69)",
            "    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by ciphrd** [comment]
Hum I see, we need to upgrade the schema being pulled as it points to an old DB with a different schema

**Comment by alexanderkorytskyi** [comment]
Hey, @ciphrd. I also tried to explore both repos last evening and maybe fix some reported bugs, but I also found errors about missing fields in Postgres. Do you have any authomation on updating the db-dump in the s3? What is the strategy for preparing such a dump? Do you need help with this?
